<?php
/**
 * Surest Plug - Web Installer & First Administrator Setup
 * For InfinityFree shared hosting setup
 */

require_once __DIR__ . '/config/app_config.php';
$lockFile = __DIR__ . '/config/installed.lock';

$isInstalled = file_exists($lockFile);
$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$isInstalled) {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = trim($_POST['db_pass'] ?? '');
    $adminName = trim($_POST['admin_name'] ?? '');
    $adminEmail = strtolower(trim($_POST['admin_email'] ?? ''));
    $adminPass = trim($_POST['admin_pass'] ?? '');
    
    if (empty($dbName) || empty($dbUser) || empty($adminName) || empty($adminEmail) || empty($adminPass)) {
        $error = 'Please complete all required fields.';
    } elseif (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) {
        $error = 'Please enter a valid administrator email.';
    } elseif (strlen($adminPass) < 8) {
        $error = 'Administrator password must be at least 8 characters long.';
    } else {
        try {
            $dsn = "mysql:host={$dbHost};dbname={$dbName};charset=utf8mb4";
            $pdo = new PDO($dsn, $dbUser, $dbPass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
            ]);
            
            // Execute SQL schema
            $sql = file_get_contents(__DIR__ . '/database.sql');
            $pdo->exec($sql);
            
            // Check if admin already exists
            $stmt = $pdo->prepare("SELECT id FROM users WHERE email = ? LIMIT 1");
            $stmt->execute([$adminEmail]);
            $existing = $stmt->fetch();
            
            $hashedPass = password_hash($adminPass, PASSWORD_BCRYPT, ['cost' => 12]);
            if ($existing) {
                $upd = $pdo->prepare("UPDATE users SET password = ?, role = 'admin', account_status = 'active' WHERE id = ?");
                $upd->execute([$hashedPass, $existing['id']]);
            } else {
                $ins = $pdo->prepare("INSERT INTO users (full_name, email, password, role, balance, account_status) VALUES (?, ?, ?, 'admin', 0.00, 'active')");
                $ins->execute([$adminName, $adminEmail, $hashedPass]);
            }
            
            // Update database.php file
            $configContent = "<?php\n" .
                "// Generated by Surest Plug Web Installer\n" .
                "define('DB_HOST', " . var_export($dbHost, true) . ");\n" .
                "define('DB_NAME', " . var_export($dbName, true) . ");\n" .
                "define('DB_USER', " . var_export($dbUser, true) . ");\n" .
                "define('DB_PASS', " . var_export($dbPass, true) . ");\n" .
                "define('DB_CHARSET', 'utf8mb4');\n\n" .
                "function getDBConnection() {\n" .
                "    static \$pdo = null;\n" .
                "    if (\$pdo === null) {\n" .
                "        \$dsn = 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=' . DB_CHARSET;\n" .
                "        \$options = [\n" .
                "            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,\n" .
                "            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n" .
                "            PDO::ATTR_EMULATE_PREPARES => false\n" .
                "        ];\n" .
                "        \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, \$options);\n" .
                "    }\n" .
                "    return \$pdo;\n" .
                "}\n";
            file_put_contents(__DIR__ . '/config/database.php', $configContent);
            
            // Lock installer
            file_put_contents($lockFile, 'Installed on ' . date('Y-m-d H:i:s'));
            $isInstalled = true;
            $success = 'Installation successfully completed! You can now log in to the admin panel.';
        } catch (Exception $e) {
            $error = 'Database Connection Failed: ' . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup & Installer — <?php echo SITE_NAME; ?></title>
    <link rel="icon" type="image/png" href="/assets/images/favicon.png">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-50 min-h-screen flex items-center justify-center p-4">
    <div class="w-full max-w-xl bg-white rounded-3xl shadow-xl border border-slate-100 p-8 sm:p-10">
        <div class="text-center mb-8">
            <img src="/assets/images/sp-logo.png" alt="Surest Plug" class="w-16 h-16 mx-auto object-contain mb-3" onerror="this.src='https://www.image2url.com/r2/default/images/1787280450296-e9b96e0a-2afe-4699-b779-c0a26af1f613.png'">
            <h1 class="text-2xl font-bold text-slate-900">Surest Plug Installer</h1>
            <p class="text-slate-500 text-sm mt-1">InfinityFree & MySQL Production Setup</p>
        </div>

        <?php if ($isInstalled && !$success): ?>
            <div class="p-6 bg-emerald-50 border border-emerald-200 rounded-2xl text-center space-y-4">
                <div class="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-full mx-auto flex items-center justify-center font-bold text-xl">✓</div>
                <h2 class="text-lg font-semibold text-emerald-900">Application Already Installed</h2>
                <p class="text-sm text-emerald-700">The database and administrator account have already been configured securely.</p>
                <div class="flex justify-center gap-3 pt-2">
                    <a href="/login.php" class="px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold rounded-xl transition-all">Go to Login</a>
                    <a href="/index.php" class="px-5 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 text-sm font-semibold rounded-xl transition-all">Homepage</a>
                </div>
            </div>
        <?php else: ?>
            <?php if ($error): ?>
                <div class="p-4 mb-6 bg-red-50 border border-red-200 rounded-2xl text-red-700 text-sm">
                    <?php echo htmlspecialchars($error); ?>
                </div>
            <?php endif; ?>

            <?php if ($success): ?>
                <div class="p-6 bg-emerald-50 border border-emerald-200 rounded-2xl text-center space-y-4">
                    <h2 class="text-lg font-semibold text-emerald-900">Setup Completed!</h2>
                    <p class="text-sm text-emerald-700"><?php echo htmlspecialchars($success); ?></p>
                    <div class="pt-2">
                        <a href="/login.php" class="inline-block px-6 py-2.5 bg-blue-600 text-white font-semibold text-sm rounded-xl hover:bg-blue-700 transition-all">Proceed to Login</a>
                    </div>
                </div>
            <?php else: ?>
                <form method="POST" class="space-y-6">
                    <div class="space-y-4">
                        <h3 class="text-sm font-bold text-slate-400 uppercase tracking-wider">MySQL Database Credentials</h3>
                        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                            <div>
                                <label class="block text-xs font-semibold text-slate-700 mb-1">MySQL Host</label>
                                <input type="text" name="db_host" value="localhost" class="w-full px-3.5 py-2 text-sm border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-600 focus:outline-none" required>
                            </div>
                            <div>
                                <label class="block text-xs font-semibold text-slate-700 mb-1">Database Name</label>
                                <input type="text" name="db_name" placeholder="if0_XXXX_surestplug" class="w-full px-3.5 py-2 text-sm border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-600 focus:outline-none" required>
                            </div>
                            <div>
                                <label class="block text-xs font-semibold text-slate-700 mb-1">Database User</label>
                                <input type="text" name="db_user" placeholder="if0_XXXX" class="w-full px-3.5 py-2 text-sm border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-600 focus:outline-none" required>
                            </div>
                            <div>
                                <label class="block text-xs font-semibold text-slate-700 mb-1">Database Password</label>
                                <input type="password" name="db_pass" placeholder="vPanel Password" class="w-full px-3.5 py-2 text-sm border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-600 focus:outline-none">
                            </div>
                        </div>
                    </div>

                    <div class="space-y-4 pt-4 border-t border-slate-100">
                        <h3 class="text-sm font-bold text-slate-400 uppercase tracking-wider">First Administrator Account</h3>
                        <div>
                            <label class="block text-xs font-semibold text-slate-700 mb-1">Admin Full Name</label>
                            <input type="text" name="admin_name" value="CHINONSO MONDAY" class="w-full px-3.5 py-2 text-sm border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-600 focus:outline-none" required>
                        </div>
                        <div>
                            <label class="block text-xs font-semibold text-slate-700 mb-1">Admin Email Address</label>
                            <input type="email" name="admin_email" value="chinonsochinix@gmail.com" class="w-full px-3.5 py-2 text-sm border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-600 focus:outline-none" required>
                        </div>
                        <div>
                            <label class="block text-xs font-semibold text-slate-700 mb-1">Admin Password</label>
                            <input type="password" name="admin_pass" placeholder="Enter password (e.g. Chinonso12)" class="w-full px-3.5 py-2 text-sm border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-600 focus:outline-none" required minlength="6">
                        </div>
                    </div>

                    <button type="submit" class="w-full py-3 bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white font-semibold rounded-xl shadow-md transition-all text-sm">
                        Initialize Database & Create Admin
                    </button>
                </form>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</body>
</html>
